[package]
name = "syn-serde"
version = "0.2.0"
authors = ["David Tolnay <dtolnay@gmail.com>", "Taiki Endo <te316e89@gmail.com>"]
edition = "2018"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/taiki-e/syn-serde"
homepage = "https://github.com/taiki-e/syn-serde"
documentation = "https://docs.rs/syn-serde"
keywords = ["serde", "serialization", "syn"]
categories = ["development-tools::procedural-macro-helpers", "encoding"]
readme = "README.md"
description = """
Library to serialize and deserialize Syn syntax trees.
"""

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]

[package.metadata.playground]
all-features = true

[workspace]
members = ["examples/json2rust", "examples/rust2json"]

[features]
json = ["serde_json"]

[dependencies]
proc-macro2 = { version = "1.0", default-features = false }
serde = { version = "1.0.99", features = ["derive"] }
serde_derive = "1.0.99" # This is necessary to make `-Z minimal-versions` build successful.
serde_json = { version = "1.0", optional = true }
syn = { version = "1.0.5", default-features = false, features = ["full"] }

[dev-dependencies]
quote = "1.0"
serde_json = "1.0"
syn = { version = "1.0", features = ["full", "extra-traits"] }
