[package]
name = "json2rust"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies]
syn-serde = { path = "../..", features = ["json"] }
syn = { version = "1", features = ["full"] }
prettyplease = "0.1.11"
quote = "1"
