[package]
name = "syn-serde-internal-codegen"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1"
fs-err = "2"
globset = "0.4"
prettyplease = "0.1"
proc-macro2 = "1"
quote = "1"
serde_json = "1"
syn = "1"
syn-codegen = "0.3"
