[package]
name = "syn-serde-internal-codegen"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>", "Nika Layzell <nika@thelayzells.com>", "Taiki Endo <te316e89@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
anyhow = "1"
fs = { package = "fs-err", version = "2" }
proc-macro2 = "1"
quote = "1"
serde_json = "1"
syn-codegen = "0.2"
tempfile = "3"
