[package]
name = "syn-serde-internal-codegen"
edition = "2021"

[dependencies]
anyhow = "1"
fs-err = "2"
globset = { version = "0.4", default-features = false }
prettyplease = "0.2"
proc-macro2 = "1"
quote = "1"
serde_json = "1"
syn = "2"
syn-codegen = "0.4"

[lints]
workspace = true
